name: studentappfirebase
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_core: ^2.24.0
  fluttertoast: ^8.2.4
  provider: ^6.1.1
  google_fonts: ^6.1.0
  connectivity_plus: ^5.0.2
  pinput: ^3.0.1
  lottie: ^2.7.0
  google_sign_in: ^6.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  flutter_slidable: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
